### ISSUE TITLE
希望与LemonPlus合作，提供帮助文档

### ISSUE THREAD

**Issue by Prurite** [iotang/Project_LemonPt#3]
lemon_pt 和 LemonPlus 属近似项目，如果双方的 contributor 合作或可增加效率。
https://github.com/Dust1404/Project_LemonPlus/issues/3#issuecomment-489517315_

**Comment by iotang** [comment]
这哪只是近似项目，LemonPt 就是 LemonPlus 的一个 Branch

**Comment by iotang** [comment]
帮助文档是写在 Wiki 里面写还是集成到 LemonPt 软件里面？

**Comment by Dust1404** [comment]
LemonPlus 的用户手册及 tex 源文件已上传，可能可以帮助进一步完善本软件的帮助文档。
Feel free to use it.
